// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Maximise():Promise<boolean>;

export function Minimise():Promise<void>;

export function Unmaximise():Promise<boolean>;
