// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function LaunchMinecraft(arg1:string):Promise<main.Result>;

export function Minimise():Promise<boolean>;

export function ToggleMaximise():Promise<boolean>;
