// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Maximise() {
  return window['go']['main']['App']['Maximise']();
}

export function Minimise() {
  return window['go']['main']['App']['Minimise']();
}

export function Unmaximise() {
  return window['go']['main']['App']['Unmaximise']();
}
